### ISSUE TITLE
customizable cython options

### ISSUE THREAD

**Issue by rickardcronholm** [anxuae/setuptools-cythonize#1]
Loving this package so far. However, finding the lack of customization a bit limiting. 

Some cython_options appear to be hardcoded like
```
            # Embed source line position
            cython_options.embed_pos_in_docstring = True
            # Generate annotated HTML page for source files
            cython_options.annotate = False
            cython_options.fast_fail = True
            cython_options.error_on_unknown_names = True
            self.compile = self.optimize = False  # noqa
```

I can't see a proper way to customizing any options, either the ones hard coded or the ones left to cython default directive.

(Also as a side note `module_name.startswith('__')` does not only catch `__init__.py` but also e.g. `__main__.py`)

**Comment by anxuae** [comment]
Hi @rickardcronholm 

Thanks for your feedback, will work on this issue soon.

**Comment by anxuae** [comment]
>Some cython_options appear to be hardcoded like

My proposal is to removed the hard-coded values and let the user define the compiler options as described in the `Cython` documentation: https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-options

>(Also as a side note module_name.startswith('__') does not only catch __init__.py but also e.g. __main__.py)

I will explicitly define the modules that have not to be compiled. However the `__main__.py` shall remain in pure python else it will not be possible to run the code using the command `python -m my package`
