### ISSUE TITLE
Cythonize install command 

### ISSUE THREAD

**Issue by davidalo** [anxuae/setuptools-cythonize#2]
I have tried this package with success to make wheels. But I couldn't make it run for a local install, I mean  `python3 setup.py install --cythonize` doesn't install it as a compiled library.

I can be interesting for performing local installations with Cython.

**Comment by davidalo** [comment]
I will research about it, but any recommendation for where to start is highly appreciated.

**Comment by anxuae** [comment]
Hi @davidalo 

Thanks for reporting, I will have a look soon

**Comment by davidalo** [comment]
I have found a solution, maybe I can perform a PR.

**Comment by anxuae** [comment]
Of course, feel free to propose a PR

**Comment by anxuae** [comment]
I found a strange way to fix it, please have a look.
However the `python setup.py install` will not install lib as an `egg` anymore, it may cause other issues...
