### ISSUE TITLE
Package available as tar.gz in Pypi

### ISSUE THREAD

**Issue by davidalo** [anxuae/setuptools-cythonize#3]
At this moment, package is only available as a wheel in Pypi. It can be useful to have it as a tarfile for multiple purposes.

**Comment by anxuae** [comment]
Do you mean a `sdist` package ? or a `bdist` package but in `tarfile` format?

**Comment by anxuae** [comment]
`sdist` package will be available on next release

**Comment by anxuae** [comment]
version 1.0.5 available
